### ISSUE TITLE
你的这个鼠标的效果和Fork me on github 是怎么弄的啊

### ISSUE THREAD

**Issue by FeeAlan** [ehlxr/ehlxr.github.io#1]

**Comment by ehlxr** [comment]
http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/

七、背景效果 这有介绍，你可以看一下

**Comment by FeeAlan** [comment]
@ehlxr 多谢
