### ISSUE TITLE
你好，请问在Next主题上搭建gitment的方法

### ISSUE THREAD

**Issue by Holton1** [ehlxr/ehlxr.github.io#2]
你好，我最近新建了一个blog，想用gitment做评论系统，看了gitment的文档，还是不太会做（目前只会套用模版），看到你在gitment下的issue。我觉得你的博客实现效果很棒，能麻烦你发一份给我吗？

我主要是引入Gitment那里不会，不知道下面那段代码要放哪里。。我的网页是hexo自动生成的，我只会把写好的.md博文放进_posts，和照着Next主题帮助改设置。。。

希望你能给我一点帮助，谢谢~

<div id="container"></div>
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
<script>
var gitment = new Gitment({
  id: '页面 ID', // 可选。默认为 location.href
  owner: '你的 GitHub ID',
  repo: '存储评论的 repo',
  oauth: {
    client_id: '你的 client ID',
    client_secret: '你的 client secret',
  },
})
gitment.render('container')
</script>

**Comment by zhangximufeng** [comment]
可不可以看看博主hexo配置，自己捣鼓了半天 连一个搜索都弹不出来

**Comment by zhangximufeng** [comment]
zhangximufeng@163.com

**Comment by ehlxr** [comment]
这个需要修改主题文件，我用的是next主题，可以发给你参考参考
